### ISSUE TITLE
IntelliJ Plugins

### ISSUE THREAD

**Issue by Miha-x64** [hbmartin/awesome-android-lint#1]
Hello. Great list!
I am a developer of IntelliJ / Android Studio [plugin](https://plugins.jetbrains.com/plugin/12690-mike-s-idea-extensions) with a lot of inspections for Android. It is not a lint check, strictly speaking. Can it be added to your list?

**Comment by hbmartin** [comment]
@Miha-x64  Thanks for the pointer! Really great checks 👏  I added it under the 'Other' section.
Have you thought about porting this to lint or detekt? At least for my company, we wouldn't be able to adopt these if we wanted due to lack of CI enforcement.

**Comment by Miha-x64** [comment]
I think IntelliJ Platform is greater than lint checks. Inspections run on the fly and provide quickfixes.
IntelliJ provides an option to [run inspections from CLI](https://www.jetbrains.com/help/idea/command-line-code-inspector.html).
